import boto3

s3=boto3.client('s3')
list=s3.list_objects(Bucket='S3-Bucket-Name')['Contents'] # replace S3-Bucket-Name by the bucket name generated by bbe_clientCloud.py
for key in list:
    s3.download_file('S3-Bucket-Name', key['Key'], key['Key']) # replace S3-Bucket-Name by the bucket name generated by bbe_clientCloud.py